name: .Net
on:
  push:
    branches:
    - main
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - main
env:
  MESHCONFIGURATION__URL: ${{ secrets.MESHCONFIGURATION__URL }}
  MESHCONFIGURATION__MAILBOXID: ${{ secrets.MESHCONFIGURATION__MAILBOXID }}
  MESHCONFIGURATION__PASSWORD: ${{ secrets.MESHCONFIGURATION__PASSWORD }}
  MESHCONFIGURATION__SHAREDKEY: ${{ secrets.MESHCONFIGURATION__SHAREDKEY }}
  MESHCONFIGURATION__TLSROOTCERTIFICATES__0: ${{ secrets.MESHCONFIGURATION__TLSROOTCERTIFICATES__0 }}
  MESHCONFIGURATION__TLSINTERMEDIATECERTIFICATES__0: ${{ secrets.MESHCONFIGURATION__TLSINTERMEDIATECERTIFICATES__0 }}
  MESHCONFIGURATION__CLIENTSIGNINGCERTIFICATE: ${{ secrets.MESHCONFIGURATION__CLIENTSIGNINGCERTIFICATE }}
jobs:
  build_windows:
    name: Build - Windows
    runs-on: windows-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test NEL.Mesh.Tests.Unit/NEL.Mesh.Tests.Unit.csproj --no-build --verbosity normal
    - name: Acceptance Tests
      run: dotnet test NEL.Mesh.Tests.Acceptance/NEL.Mesh.Tests.Acceptance.csproj --no-build --verbosity normal
  build_ubuntu:
    name: Build - Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v4
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      run: dotnet test NEL.Mesh.Tests.Unit/NEL.Mesh.Tests.Unit.csproj --no-build --verbosity normal
    - name: Acceptance Tests
      run: dotnet test NEL.Mesh.Tests.Acceptance/NEL.Mesh.Tests.Acceptance.csproj --no-build --verbosity normal
